### ISSUE TITLE
Error whilst serializing AvailableCommandsPacket

### ISSUE THREAD

**Issue by Heath123** [CloudburstMC/Protocol#100]
When using ProxyPass with the Bedrock Dedicated Server (1.16.200) I get this error:
https://hastebin.com/faluqorica.sql
I'm using https://github.com/CloudburstMC/ProxyPass/pull/25

**Comment by Alemiz112** [comment]
Hello, the log seems to be empty for me. What server software have you used as downstream?

**Comment by Heath123** [comment]
I think it expired
I did say in the issue that I used the Bedrock Dedicated Server, but th is was a while ago so I can't remember much else
I think it might have been fixed by setting the blocking item properly
