### ISSUE TITLE
UnsupportedOperationException: Unknown CraftingDataType ID: -49

### ISSUE THREAD

**Issue by Heath123** [CloudburstMC/Protocol#101]
When using ProxyPass with the Bedrock Dedicated Server (1.16.200) I get this error:
https://gist.github.com/Heath123/26c94cb120b1cc7ab3a53658b8b83acd
I'm using https://github.com/CloudburstMC/ProxyPass/pull/25

**Comment by Alemiz112** [comment]
Hi, you have to set `shieldBlockingId` to downstream and upstream session. Otherwise packets which contain `ItemData` might not be serialized correctly.

**Comment by Heath123** [comment]
Oh, this was the same thing as #102, sorry
