### ISSUE TITLE
PacketSerializeException: Error whilst deserializing CreativeContentPacket(contents=null)

### ISSUE THREAD

**Issue by Heath123** [CloudburstMC/Protocol#102]
When using ProxyPass with the Bedrock Dedicated Server (1.16.200) I get this error:
https://hastebin.com/hafipaguzu.properties
I'm using https://github.com/CloudburstMC/ProxyPass/pull/25

**Comment by KCodeYT** [comment]
session.getHardcodedBlockingId().set(355);

**Comment by Heath123** [comment]
Oh, OK, thank you, shouldn't it depend on what the server sends in a proxy or will it always be that?

**Comment by Alemiz112** [comment]
> Oh, OK, thank you, shouldn't it depend on what the server sends in a proxy or will it always be that?

Yes, it may be different by server. You can get correct `shieldBlockingId` from item entries in `StartGamePacket`.

**Comment by Heath123** [comment]
I should close this because it isn't a Protocol issue

**Comment by Camotoy** [comment]
Feel free to comment on this in my PR. It should be an easy fix.

**Comment by Heath123** [comment]
I think I know how to fix it now but I will
