### ISSUE TITLE
Update Support for Bedrock 1.16

### ISSUE THREAD

**Issue by werwolf2303** [CloudburstMC/Protocol#60]
I have a Problem the BedrockProtocol doesnt support MCPE 1.16, ist possible to Update that?

**Comment by Liato-GR** [comment]
The normal Nukkitx is just currently a bit Struggeling, but you could use the 1.16 Branch [https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/feature%252F1.16/](url) otherwise you need to wait.

**Comment by Sleepybear** [comment]
Also the develop branch of the protocol library supports 1.16

**Comment by werwolf2303** [comment]
Thank you for the quick help
